### ISSUE TITLE
PLEASE ADD THE LABEL  **HACKTOBERFEST-ACCEPTED**

### ISSUE THREAD

**Issue by abheer18** [sauravgpt2/hacktoberfest36_2021#157]
@sauravgpt2  , ### Please add the label of  **HACKTOBERFEST-ACCEPTED** on the PR's, 
it's the rule of HACKTOBEREST 2021 that every PR should have this label otherwise it will not be accepted.
My PR number is  - **5ff9d66**

**Comment by sauravgpt2** [comment]
Done
